import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { switzer } from "./fonts/font";
import Nav from "./ui/navbar/nav";
import Footer from "./ui/footer/footer";

export const metadata: Metadata = {
  title: "Crypto Assets Weath Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${switzer.variable}  antialiased  max-w-640 mx-auto`}>
        <Nav />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
